# app/core/rag_config.py
# This file centralizes all constants for the RAG (Retrieval-Augmented Generation) system.

# The cosine similarity score above which a node is considered relevant.
SIMILARITY_THRESHOLD = 0.75

# The dimensionality of the vectors generated by our embedding model.
# This MUST match the value in the Neo4j vector index configuration.
VECTOR_DIMENSIONS = 768

# The maximum number of candidate nodes to retrieve from the vector index for consideration.
MAX_SEMANTIC_CANDIDATES = 100